sonar.projectKey=Gemini-Clone-DevSecOps
sonar.projectName=Gemini Clone DevSecOps
sonar.sources=src
sonar.sourceEncoding=UTF-8

sonar.exclusions=**/node_modules/**,**/.next/**,**/coverage/**,**/public/**

sonar.typescript.tsconfigPath=tsconfig.json
